timeout:0

/Bebok OS
    protocol:limine

    # Disable KASLR (Kernel Address Space Layout Randomization), it is enabled by default for relocatable kernels
    kaslr:no

    # Limit the maximum paging mode to one of the following
    max_paging_mode:4level

    # force CGA text mode
    graphics:no

    kernel_path:boot():/kernel.elf
